# Scala eval

FROM dockerfile/nodejs
MAINTAINER Tomasz Szymanski, tom@softwaremill.com
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV LC_ALL en_US.UTF-8
ENTRYPOINT [ "node", "-e" ]